### PR TITLE
CUDA 12.4

### LINKED ISSUE #226: Unsupported cuda toolkit version: `12040`
```
Caused by:
  process didn't exit successfully: `/home/callen/.cargo/cache/release/build/cudarc-5f6c1d160b387f41/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-env-changed=CUDA_ROOT
  cargo:rerun-if-env-changed=CUDA_PATH
  cargo:rerun-if-env-changed=CUDA_TOOLKIT_ROOT_DIR

  --- stderr
  thread 'main' panicked at /home/callen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cudarc-0.11.0/build.rs:52:14:
  Unsupported cuda toolkit version: `12040`. Please raise a github issue.
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

It said,

>Please raise a github issue.

so here I am. I'm new to GPU compute for the most part so I'm not sure how much delta to expect from one minor CUDA version  to the next. Gonna vendor the library and see how far I get doing something lazy and ignorant.

### PR DESCRIPTION
**Pull request by bitemyapp**
Fixes #226 

No idea if I did this right. I had some mystifying issues with the types until I added `cudnn_backend.h` to the wrapper header for the bindgen.

Remaining issue: no idea what happened to `CUDNN_DATA_BOOLEAN`.

image

image

It uhh, disappeared? I can't find anything in the CUDA 12.4 release notes about this so I have to believe that I've done something wrong on that account. Fortunately, I'm not using cuDNN and don't know why I would want bools so I don't think it's a blocker for what I'm doing.

### CODE REVIEW

File: src/nccl/sys/mod.rs [hunk 1]
```diff
@@ -28,6 +28,12 @@ mod sys_12030;
 #[cfg(feature = "cuda-12030")]
 pub use sys_12030::*;
 
+#[cfg(feature = "cuda-12040")]
+mod sys_12040;
+#[cfg(feature = "cuda-12040")]
+pub use sys_12040::*;
+
+
```
Comment (coreylowman) [inline src/nccl/sys/mod.rs:36]:
```suggestion
```

**Comment by coreylowman** [comment]
That's weird regarding the boolean dtype. I'm thinking we can merge this for now and fix that in a patch version if it comes up as an issue?
